services:
  - type: web
    name: youtube-downloader
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn backend.app:app"
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://sammedghattad2413:<1234567>@cluster0.m47ec.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0